/**
 * Lazy accessor for the generated land mask.
 *
 * The decoded mask is built once per page load and shared, so mounting the
 * globe twice (React StrictMode, a re-render) never pays the decode twice.
 * `src/landmask.ts` is generated by `scripts/gen-landmask.ts` from Natural
 * Earth 1:110m land — see `npm run land:gen`.
 */
import { LAND_MASK_BITS_BASE64, LAND_MASK_HEIGHT, LAND_MASK_WIDTH } from "../landmask";
import { decodeLandMask, type LandMask } from "./geo";

let cached: LandMask | null = null;

export function getLandMask(): LandMask {
  cached ??= decodeLandMask(LAND_MASK_BITS_BASE64, LAND_MASK_WIDTH, LAND_MASK_HEIGHT);
  return cached;
}
