"""Deterministic science for harmonizing MODIS and VIIRS hotspots.

One callable facade for anomalies: ``anomaly(...)`` scores a date (z-score,
percentile, flag) while ``anomaly.anomaly_report(...)`` is the percentile-rank
report the API contract needs.
"""

from .anomaly import anomaly, anomaly_payload, anomaly_report
from .baseline import doy, percentile, seasonal_baseline
from .grid import (
    MODIS_MASK,
    STREAM_BITS,
    VIIRS_MASK,
    CellDay,
    collapse_cell_days,
    grid_snap,
    merge_cell_days,
    to_cells,
    to_series,
)
from .harmonize import (
    DEFAULT_CELL_KM,
    DEFAULT_WINDOW_DAYS,
    REFERENCE_LATITUDE_DEG,
    anomaly_score,
    baseline_percentiles,
    cell_bounds,
    cell_id,
    daily_series,
    degrees_per_lat,
    degrees_per_lon,
    family_daily_frames,
    grid_index,
    harmonized_series,
    parse_cell_id,
    raw_series,
    to_grid,
    years_used,
)
from .schema import (
    CANONICAL_COLUMNS,
    MIN_CONFIDENCE,
    MODIS,
    REQUIRED_COLUMNS,
    VIIRS,
    VIIRS_CONFIDENCE_MAP,
    Detection,
    confidence_mapping,
    confidence_to_numeric,
    infer_family,
    normalize,
    quality_filter,
)
from .season import critical_period
from .series_util import BIN_DAYS, bin_of_doy
from .validate import (
    Correlation,
    ValidationReport,
    cell_sweep,
    correlation_stats,
    family_date_range,
    overlap_validation,
    overlap_window,
    pearson,
    ranks,
    spearman,
    validate_overlap,
)

# Public surface; kept sorted (ruff RUF022).
__all__ = [
    "BIN_DAYS",
    "CANONICAL_COLUMNS",
    "DEFAULT_CELL_KM",
    "DEFAULT_WINDOW_DAYS",
    "MIN_CONFIDENCE",
    "MODIS",
    "MODIS_MASK",
    "REFERENCE_LATITUDE_DEG",
    "REQUIRED_COLUMNS",
    "STREAM_BITS",
    "VIIRS",
    "VIIRS_CONFIDENCE_MAP",
    "VIIRS_MASK",
    "CellDay",
    "Correlation",
    "Detection",
    "ValidationReport",
    "anomaly",
    "anomaly_payload",
    "anomaly_report",
    "anomaly_score",
    "baseline_percentiles",
    "bin_of_doy",
    "cell_bounds",
    "cell_id",
    "cell_sweep",
    "collapse_cell_days",
    "confidence_mapping",
    "confidence_to_numeric",
    "correlation_stats",
    "critical_period",
    "daily_series",
    "degrees_per_lat",
    "degrees_per_lon",
    "doy",
    "family_daily_frames",
    "family_date_range",
    "grid_index",
    "grid_snap",
    # ``harmonize`` is also reachable as the submodule of the same name
    "harmonize",
    "harmonized_series",
    "infer_family",
    "merge_cell_days",
    "normalize",
    "overlap_validation",
    "overlap_window",
    "parse_cell_id",
    "pearson",
    "percentile",
    "quality_filter",
    "ranks",
    "raw_series",
    "seasonal_baseline",
    "spearman",
    "to_cells",
    "to_grid",
    "to_series",
    "validate_overlap",
    "years_used",
]
